name: "restore"
version: "0.1.0"
usage: "restore last deployed release to originial state"
description: "restore last deployed release to original state"
command: "$HELM_PLUGIN_DIR/bin/restore"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
